version: '3.7'
services:
  db:
    image: mysql
    container_name: mysql-container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  api:
    build: "./Api"
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
