version: '3.7'
services:
  db:
    image: mysql:5.7
    container_name: mysql-container
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_USER=lima
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=auth
      - MYSQL_ROOT_PASSWORD=123456
  
    ports: 
      - "3307:3306"
    networks:
      - auth_project_net

  api:
    build: "./Api"
    container_name: api
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_DATABASE=auth
      - DB_PASSWORD=123456
      - DB_PORT=3307
    networks:
      - auth_project_net


networks:
  auth_project_net:
    driver: bridge
